### ISSUE TITLE
This is not an issue

### ISSUE THREAD

**Issue by maelle** [Gibbsdavidl/CatterPlots#2]
I just wanted to say I'm inspired by your plots for my own small cat plotting project https://github.com/masalmon/colourlovers_patterns ;-)

**Comment by Gibbsdavidl** [comment]
Love the marbleized bar plots… highly luxurious.   ;)

 
—
David L Gibbs
Postdoc Researcher
Shmulevich Group 
Institute for Systems Biology 
www.systemsbiology.org <http://www.systemsbiology.org/> 
206.732.1494
