### ISSUE TITLE
RGB colors are hard to use!

### ISSUE THREAD

**Issue by Gibbsdavidl** [Gibbsdavidl/CatterPlots#6]
Allow the use of color names, and convert to RGB using col2rgb().

> col2rgb("blue", alpha=T)
      [,1]
red      0
green    0
blue   255
alpha  255
https://stat.ethz.ch/R-manual/R-devel/library/grDevices/html/col2rgb.html

**Comment by Gibbsdavidl** [comment]
Now we're on HEX colors. Cool.

**Comment by calpan** [comment]
The standard R colors output by colors() work too without any modifications.
